version: "3.4"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:latest
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
  kibana:
    image: docker.elastic.co/kibana/kibana:latest
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  messagingservicedb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: messagingservicedb
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  messagingservice:
    build: ./src
    ports:
      - "5000:5000"
    env_file:
      - ./src/.env
    depends_on:
      - kibana
